//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class color
    {
        public color()
        {
            this.products = new HashSet<product>();
        }
    
        public int colorid { get; set; }
        public string colorname { get; set; }
        public string colorcode { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
