//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer
    {
        public customer()
        {
            this.comments = new HashSet<comment>();
            this.product_order = new HashSet<product_order>();
            this.wish_list = new HashSet<wish_list>();
        }
    
        public System.Guid cusid { get; set; }
        public string cusfirstname { get; set; }
        public string cuslastname { get; set; }
        public Nullable<int> idcustomer_information { get; set; }
    
        public virtual aspnet_Users aspnet_Users { get; set; }
        public virtual ICollection<comment> comments { get; set; }
        public virtual ICollection<product_order> product_order { get; set; }
        public virtual ICollection<wish_list> wish_list { get; set; }
        public virtual customer_information customer_information { get; set; }
    }
}
