//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class customer_information
    {
        public customer_information()
        {
            this.customers = new HashSet<customer>();
            this.product_order = new HashSet<product_order>();
            this.product_order1 = new HashSet<product_order>();
        }
    
        public int id { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string phonenumber1 { get; set; }
        public string phonenumber2 { get; set; }
        public Nullable<System.DateTime> birthday { get; set; }
        public string gender { get; set; }
        public string country { get; set; }
        public string region_state { get; set; }
        public string city { get; set; }
        public string post_code { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string email { get; set; }
    
        public virtual ICollection<customer> customers { get; set; }
        public virtual ICollection<product_order> product_order { get; set; }
        public virtual ICollection<product_order> product_order1 { get; set; }
    }
}
