//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class discount
    {
        public discount()
        {
            this.products = new HashSet<product>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public System.DateTime datebegin { get; set; }
        public System.DateTime datefinal { get; set; }
        public string discountintro { get; set; }
        public Nullable<int> image { get; set; }
        public Nullable<double> percentage { get; set; }
    
        public virtual imagetb imagetb { get; set; }
        public virtual ICollection<product> products { get; set; }
    }
}
