//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class imagetb
    {
        public imagetb()
        {
            this.advertisements = new HashSet<advertisement>();
            this.image_product = new HashSet<image_product>();
            this.image_product1 = new HashSet<image_product>();
            this.image_slide = new HashSet<image_slide>();
            this.image_slide1 = new HashSet<image_slide>();
            this.products = new HashSet<product>();
        }
    
        public int imgid { get; set; }
        public string url { get; set; }
    
        public virtual ICollection<advertisement> advertisements { get; set; }
        public virtual discount discount { get; set; }
        public virtual ICollection<image_product> image_product { get; set; }
        public virtual ICollection<image_product> image_product1 { get; set; }
        public virtual ICollection<image_slide> image_slide { get; set; }
        public virtual ICollection<image_slide> image_slide1 { get; set; }
        public virtual ICollection<product> products { get; set; }
        public virtual payment_method payment_method { get; set; }
    }
}
