//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class image_slide
    {
        public int id { get; set; }
        public Nullable<int> imgthumbid { get; set; }
        public int imgid { get; set; }
        public Nullable<int> proid { get; set; }
        public string imgdescription { get; set; }
    
        public virtual imagetb imagetb { get; set; }
        public virtual imagetb imagetb1 { get; set; }
        public virtual product product { get; set; }
    }
}
