//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewFashionDBEntities : DbContext
    {
        public NewFashionDBEntities()
            : base("name=NewFashionDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<advertisement> advertisements { get; set; }
        public DbSet<aspnet_Applications> aspnet_Applications { get; set; }
        public DbSet<aspnet_Membership> aspnet_Membership { get; set; }
        public DbSet<aspnet_Paths> aspnet_Paths { get; set; }
        public DbSet<aspnet_PersonalizationAllUsers> aspnet_PersonalizationAllUsers { get; set; }
        public DbSet<aspnet_PersonalizationPerUser> aspnet_PersonalizationPerUser { get; set; }
        public DbSet<aspnet_Profile> aspnet_Profile { get; set; }
        public DbSet<aspnet_Roles> aspnet_Roles { get; set; }
        public DbSet<aspnet_SchemaVersions> aspnet_SchemaVersions { get; set; }
        public DbSet<aspnet_Users> aspnet_Users { get; set; }
        public DbSet<aspnet_WebEvent_Events> aspnet_WebEvent_Events { get; set; }
        public DbSet<brand> brands { get; set; }
        public DbSet<category> categories { get; set; }
        public DbSet<color> colors { get; set; }
        public DbSet<comment> comments { get; set; }
        public DbSet<customer> customers { get; set; }
        public DbSet<customer_information> customer_information { get; set; }
        public DbSet<delivery_method> delivery_method { get; set; }
        public DbSet<discount> discounts { get; set; }
        public DbSet<image_product> image_product { get; set; }
        public DbSet<image_slide> image_slide { get; set; }
        public DbSet<imagetb> imagetbs { get; set; }
        public DbSet<material> materials { get; set; }
        public DbSet<order_detail> order_detail { get; set; }
        public DbSet<payment_method> payment_method { get; set; }
        public DbSet<product> products { get; set; }
        public DbSet<product_order> product_order { get; set; }
        public DbSet<shipping_method> shipping_method { get; set; }
        public DbSet<shopping_cart> shopping_cart { get; set; }
        public DbSet<size> sizes { get; set; }
        public DbSet<sysdiagram> sysdiagrams { get; set; }
        public DbSet<wish_list> wish_list { get; set; }
    }
}
