//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class order_detail
    {
        public int id { get; set; }
        public int ordid { get; set; }
        public int proid { get; set; }
        public int ordquantity { get; set; }
        public int ordsaleprice { get; set; }
        public int ordtotalprice { get; set; }
        public string currency_code { get; set; }
    
        public virtual product_order product_order { get; set; }
        public virtual product product { get; set; }
    }
}
