//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class product_order
    {
        public product_order()
        {
            this.order_detail = new HashSet<order_detail>();
        }
    
        public int ordid { get; set; }
        public System.Guid cusid { get; set; }
        public int idbuyer_information { get; set; }
        public int idarrival_information { get; set; }
        public int iddelivery_method { get; set; }
        public Nullable<int> idpayment_method { get; set; }
        public Nullable<int> idshipping_method { get; set; }
        public Nullable<System.DateTime> ordcreate_date { get; set; }
        public Nullable<int> ordstatus { get; set; }
    
        public virtual customer customer { get; set; }
        public virtual customer_information customer_information { get; set; }
        public virtual customer_information customer_information1 { get; set; }
        public virtual delivery_method delivery_method { get; set; }
        public virtual ICollection<order_detail> order_detail { get; set; }
        public virtual payment_method payment_method { get; set; }
        public virtual shipping_method shipping_method { get; set; }
    }
}
