//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class size
    {
        public size()
        {
            this.products = new HashSet<product>();
        }
    
        public int sizeid { get; set; }
        public string sizename { get; set; }
        public string sizenumber { get; set; }
    
        public virtual ICollection<product> products { get; set; }
    }
}
