//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NewFashionBLL
{
    using System;
    using System.Collections.Generic;
    
    public partial class variety
    {
        public variety()
        {
            this.product_variety = new HashSet<product_variety>();
        }
    
        public int varid { get; set; }
        public string varname { get; set; }
        public Nullable<int> varparent { get; set; }
    
        public virtual ICollection<product_variety> product_variety { get; set; }
    }
}
